version: '3'

services:
  rust-env-dev:
    build: 
      context: .
      args:
      - uid=1001
      - gid=1001
      - username=ruser
      - project_name=rustenv
    container_name: rust-tutorial-v1-dev
    image: rust-tutorial-v1-dev-image
    shm_size: '24gb'
    tty: true
    volumes: 
      - $PWD:/home/ruser/rustenv
    command: '/bin/bash'
    ports:
      - 16581-16590:16581-16590